# Generated by Django 5.1.4 on 2024-12-15 12:25

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('F:/Projects/Doc_management/backend/doc_management_back_end/static/documents')),
        ),
    ]
